// apps/site/src/components/PointDetailsForm.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import SnowflakeIcon from "phosphor-svelte/lib/SnowflakeIcon";
  import type { Audience, Dispenser, EditExtras } from "@water-run/core/schemas";
  import { NOTE_MAX, hasQuickTag, normalizeNote, toggleQuickTag } from "@water-run/core/note";
  import { audienceFromTags } from "@/lib/audience";
  import { dispenserFromTags } from "@/lib/dispenser";
  import AudienceToggle from "@/components/AudienceToggle.svelte";
  import DispenserToggle from "@/components/DispenserToggle.svelte";

  const QUICK_TAGS = [
    "Not draining",
    "Low water pressure",
    "One fountain not running",
    "Bottle filler not running",
  ];

  let {
    tags,
    busy,
    submitLabel,
    submitIcon,
    submitClassName = "bg-green-600 hover:bg-green-700",
    onSubmit,
    isRemoved = false,
    isOutOfOrder = false,
    isBroken = false,
  }: {
    tags: Record<string, string>;
    busy: boolean;
    submitLabel: string;
    submitIcon?: Snippet;
    submitClassName?: string;
    onSubmit: (extras?: EditExtras) => void;
    isRemoved?: boolean;
    isOutOfOrder?: boolean;
    isBroken?: boolean;
  } = $props();

  // Derive initial values from tags (tags identity is stable per popup).
  let seasonal = $state(tags.seasonal === "yes");
  let audience = $state<Audience>(audienceFromTags(tags));
  let dispenser = $state<Dispenser>(dispenserFromTags(tags));
  let note = $state(tags.note ?? tags.description ?? "");
  let error = $state<string | null>(null);

  // Each pill's next note, or null when adding it would overflow NOTE_MAX.
  let quickTags = $derived(
    QUICK_TAGS.map((tag) => ({
      tag,
      active: hasQuickTag(note, tag),
      next: toggleQuickTag(note, tag),
    })),
  );

  function buildExtras(cleaned: string): EditExtras | undefined {
    if (isRemoved) {
      return cleaned ? { note: cleaned } : undefined;
    }
    const extras: EditExtras = { audience, dispenser };
    if (seasonal && !isOutOfOrder) extras.seasonal = true;
    if (cleaned) extras.note = cleaned;
    return Object.keys(extras).length ? extras : undefined;
  }

  // Refuse a note the server's EditExtras schema would reject. The note is the
  // only field here it can reject, and a core test pins NOTE_MAX to its limit.
  function submit() {
    const cleaned = normalizeNote(note);
    if (cleaned.length > NOTE_MAX) {
      error = `Shorten the note to ${NOTE_MAX} characters (it has ${cleaned.length}).`;
      return;
    }
    onSubmit(buildExtras(cleaned));
  }
</script>

<div class="flex flex-col gap-2.5">
  {#if isRemoved}
    <div class="rounded border border-red-200 bg-red-50 p-2 text-xs font-medium text-red-700">
      Confirm marking this fountain as removed.
    </div>
  {:else}
    <AudienceToggle value={audience} onChange={(a) => (audience = a)} />
    <DispenserToggle value={dispenser} onChange={(d) => (dispenser = d)} />
    {#if !isOutOfOrder}
      <label
        class="flex cursor-pointer items-center justify-between rounded-lg border p-2.5 transition {seasonal
          ? 'border-sky-500 bg-sky-50/70'
          : 'border-neutral-200 bg-neutral-50 hover:bg-neutral-100'}"
      >
        <div class="flex items-center gap-2.5">
          <input
            type="checkbox"
            bind:checked={seasonal}
            class="size-4 cursor-pointer rounded border-neutral-300 accent-sky-600"
          />
          <div class="flex flex-col">
            <span class="text-xs font-bold text-neutral-900">Seasonal fountain</span>
            <span class="text-[11px] font-medium text-neutral-500">Runs only part of the year</span>
          </div>
        </div>
        <SnowflakeIcon
          size={18}
          class={seasonal ? "text-sky-600" : "text-neutral-400"}
          weight={seasonal ? "fill" : "regular"}
        />
      </label>
    {/if}
  {/if}

  {#if isBroken}
    <div class="flex flex-col gap-1.5 pt-1">
      <span class="text-[11px] font-bold tracking-wider text-neutral-600 uppercase">
        What's wrong with the fountain?
      </span>
      <div class="flex flex-wrap gap-1">
        {#each quickTags as { tag, active, next } (tag)}
          <button
            type="button"
            disabled={next === null}
            aria-pressed={active}
            onclick={() => {
              if (next === null) return;
              note = next;
              error = null;
            }}
            class="rounded border px-2 py-1 text-[11px] font-medium transition disabled:opacity-40 {active
              ? 'border-amber-600 bg-amber-500 text-white'
              : 'border-neutral-200 bg-neutral-50 text-neutral-700 hover:bg-neutral-100'}"
          >
            {tag}
          </button>
        {/each}
      </div>
      {#if quickTags.some((q) => q.next === null)}
        <span class="text-[11px] font-medium text-neutral-500">
          Note is full. Shorten it to add more.
        </span>
      {/if}
    </div>
  {/if}

  <textarea
    bind:value={note}
    oninput={() => (error = null)}
    placeholder={isBroken ? "Describe what's wrong…" : "Add a public note…"}
    rows={2}
    maxlength={NOTE_MAX}
    class="resize-none rounded-md border border-neutral-300 px-2 py-1.5 text-xs text-neutral-800 placeholder:text-neutral-400 focus:border-blue-500 focus:ring-1 focus:ring-blue-500 focus:outline-none"
  ></textarea>
  {#if error}
    <span class="text-[11px] font-semibold text-red-600">{error}</span>
  {/if}
  <button
    disabled={busy}
    onclick={submit}
    class="flex items-center justify-center gap-1.5 rounded-md py-2 text-xs font-semibold text-white shadow-sm transition disabled:opacity-50 {submitClassName}"
  >
    {@render submitIcon?.()}
    {submitLabel}
  </button>
</div>

// apps/mobile/src/components/PointDetailsForm.tsx
import { useMemo, useState } from "react";
import { Pressable, Text, View } from "react-native";
import { CheckCircleIcon } from "phosphor-react-native/src/icons/CheckCircle";
import { SnowflakeIcon } from "phosphor-react-native/src/icons/Snowflake";
import type { Audience, Dispenser, EditExtras } from "@water-run/core/schemas";
import { audienceFromTags } from "@water-run/core/audience";
import { dispenserFromTags } from "@water-run/core/dispenser";
import { NOTE_MAX, hasQuickTag, normalizeNote, toggleQuickTag } from "@water-run/core/note";
import { AudienceToggle } from "./AudienceToggle";
import { DispenserToggle } from "./DispenserToggle";
import { TextField } from "./ui/TextField";

const QUICK_TAGS = [
  "Not draining",
  "Low water pressure",
  "One fountain not running",
  "Bottle filler not running",
];

// The color of a filled button's label and icon. Light (white) on the
// saturated fills; dark on a light fill such as amber, where white falls
// under 3:1 contrast.
export type Ink = "light" | "dark";
export const INK: Record<Ink, { text: string; hex: string }> = {
  light: { text: "text-white", hex: "#ffffff" },
  dark: { text: "text-base", hex: "#0c0d0a" },
};

type Props = {
  tags: Record<string, string>;
  submitLabel: string;
  SubmitIcon?: typeof CheckCircleIcon;
  submitBox?: string;
  submitInk?: Ink;
  onSubmit: (extras?: EditExtras) => void;
  onCancel?: () => void;
  isRemoved?: boolean;
  isOutOfOrder?: boolean;
  isBroken?: boolean;
};

export function PointDetailsForm({
  tags,
  submitLabel,
  SubmitIcon = CheckCircleIcon,
  submitBox = "bg-green-600",
  submitInk = "light",
  onSubmit,
  onCancel,
  isRemoved = false,
  isOutOfOrder = false,
  isBroken = false,
}: Props) {
  // Derive initial values from tags — recalculated when `tags` identity changes.
  const defaults = useMemo(
    () => ({
      audience: audienceFromTags(tags),
      dispenser: dispenserFromTags(tags),
      seasonal: tags.seasonal === "yes",
      note: tags.note ?? tags.description ?? "",
    }),
    [tags],
  );

  const [audience, setAudience] = useState<Audience>(defaults.audience);
  const [dispenser, setDispenser] = useState<Dispenser>(defaults.dispenser);
  const [seasonal, setSeasonal] = useState(defaults.seasonal);
  const [note, setNote] = useState(defaults.note);
  const [error, setError] = useState<string | null>(null);

  function editNote(next: string) {
    setNote(next);
    setError(null);
  }

  // Each pill's next note, or null when adding it would overflow NOTE_MAX.
  const quickTags = QUICK_TAGS.map((tag) => ({
    tag,
    active: hasQuickTag(note, tag),
    next: toggleQuickTag(note, tag),
  }));

  function handleSubmit() {
    const cleaned = normalizeNote(note);
    // Stop here rather than queue an edit the server will reject for good:
    // only the user can shorten their note. The note is the one free-text
    // field EditExtras can refuse (a core test pins NOTE_MAX to its limit), so
    // this avoids pulling zod into the app bundle just to safeParse.
    if (cleaned.length > NOTE_MAX) {
      setError(`Shorten the note to ${NOTE_MAX} characters (it has ${cleaned.length}).`);
      return;
    }
    if (isRemoved) {
      onSubmit(cleaned ? { note: cleaned } : undefined);
      return;
    }
    const extras: EditExtras = { audience, dispenser };
    if (seasonal && !isOutOfOrder) extras.seasonal = true;
    if (cleaned) extras.note = cleaned;
    onSubmit(extras);
  }

  return (
    <View className="gap-3.5">
      {isRemoved ? (
        <View className="rounded-xl border border-red-300 bg-red-100 p-4">
          <Text className="text-sm font-bold text-red-950">
            Confirm there&apos;s no fountain here.
          </Text>
        </View>
      ) : (
        <>
          <AudienceToggle value={audience} onChange={setAudience} />
          <DispenserToggle value={dispenser} onChange={setDispenser} />

          {/* Seasonal checkbox hidden on out of order page */}
          {!isOutOfOrder ? (
            <Pressable
              onPress={() => setSeasonal((s) => !s)}
              accessibilityRole="checkbox"
              accessibilityState={{ checked: seasonal }}
              accessibilityLabel="Seasonal fountain"
              className={`flex-row items-center justify-between rounded-xl border p-4 ${
                seasonal ? "border-info-500 bg-info-50" : "border-border bg-surface-deep"
              }`}
            >
              <View className="flex-row items-center gap-3">
                <View
                  className={`h-6 w-6 items-center justify-center rounded-lg border ${
                    seasonal ? "border-info-600 bg-info-600" : "border-border bg-white"
                  }`}
                >
                  {seasonal ? <Text className="text-xs font-black text-white">✓</Text> : null}
                </View>
                <View className="gap-0.5">
                  <Text className="text-base text-sm font-bold">Seasonal fountain</Text>
                  <Text className="text-muted text-xs font-semibold">
                    Runs only part of the year
                  </Text>
                </View>
              </View>
              <SnowflakeIcon
                size={20}
                color={seasonal ? "#0284c7" : "#57544a"}
                weight={seasonal ? "fill" : "regular"}
              />
            </Pressable>
          ) : null}
        </>
      )}

      {/* "Partially working" issue details + quick tag pills */}
      {isBroken ? (
        <View className="gap-2 pt-1">
          <Text className="text-base text-xs font-bold tracking-wider uppercase">
            What&apos;s wrong with the fountain?
          </Text>
          <View className="flex-row flex-wrap gap-1.5 pb-1">
            {quickTags.map(({ tag, active, next }) => (
              <Pressable
                key={tag}
                onPress={() => next !== null && editNote(next)}
                disabled={next === null}
                accessibilityRole="button"
                accessibilityState={{ selected: active, disabled: next === null }}
                // Half the 6px gap, so neighbouring pills' targets never overlap.
                hitSlop={3}
                className={`rounded-lg border px-2.5 py-2 ${
                  active ? "border-amber-600 bg-amber-500" : "border-border bg-surface-deep"
                } ${next === null ? "opacity-40" : ""}`}
              >
                <Text className={`text-xs font-bold ${active ? "text-white" : "text-base"}`}>
                  {tag}
                </Text>
              </Pressable>
            ))}
          </View>
          {quickTags.some((q) => q.next === null) ? (
            <Text className="text-muted text-xs font-semibold">
              Note is full. Shorten it to add more.
            </Text>
          ) : null}
        </View>
      ) : null}

      <View className="gap-1.5">
        <Text className="text-base text-xs font-bold tracking-wider uppercase">
          {isBroken ? "Details / Note" : "Public Note"}
        </Text>
        <TextField
          value={note}
          onChangeText={editNote}
          placeholder={isBroken ? "Describe what's wrong…" : "Add a public note (optional)"}
          placeholderTextColor="#57544a"
          multiline
          maxLength={NOTE_MAX}
          className="border-border min-h-20 rounded-xl border bg-white p-3.5 text-base text-sm font-medium"
        />
        {error ? <Text className="text-sm font-semibold text-red-600">{error}</Text> : null}
      </View>

      <View className="flex-row gap-3 pt-2">
        {onCancel ? (
          // Intrinsic width, so the submit label keeps the rest of the row.
          <Pressable
            onPress={onCancel}
            accessibilityRole="button"
            className="border-border bg-surface-deep items-center justify-center rounded-xl border px-4 py-3"
          >
            <Text className="text-base font-bold">Back</Text>
          </Pressable>
        ) : null}
        <Pressable
          onPress={handleSubmit}
          accessibilityRole="button"
          className={`flex-1 flex-row items-center justify-center gap-2 rounded-xl px-4 py-3 ${submitBox}`}
        >
          <SubmitIcon size={18} color={INK[submitInk].hex} weight="bold" />
          <Text className={`text-base font-bold ${INK[submitInk].text}`}>{submitLabel}</Text>
        </Pressable>
      </View>
    </View>
  );
}
